# Generated by Django 4.2.5 on 2023-10-02 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(default='<span class="badge bg-primary ms-2">New</span>', max_length=700),
        ),
    ]
