# Generated by Django 4.2.5 on 2023-10-02 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='/static/img/404.png', upload_to='App/media/products/'),
        ),
    ]
