# Generated by Django 4.2.5 on 2023-10-02 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0012_alter_badge_code_alter_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='code_price',
            field=models.CharField(default='<s>{{product.price}}</s><strong class="ms-2 text-danger">{{(product.price)*(10/100)}}</strong>', max_length=700),
        ),
    ]
