# Generated by Django 4.2.5 on 2023-10-02 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0013_badge_code_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='code_price',
            field=models.CharField(default='<s>{{product.price|safe}}</s><strong class="ms-2 text-danger">{{product.get_price_with_discount()|safe}}</strong>', max_length=700),
        ),
    ]
