# Generated by Django 4.2.5 on 2023-10-02 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0016_discountedprice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DiscountedPrice',
        ),
    ]
