# Generated by Django 4.2.5 on 2023-10-11 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0019_discount_alter_product_type_delete_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.ForeignKey(default='New', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='App.badge'),
        ),
    ]
