# Generated by Django 4.2.5 on 2023-10-11 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0020_alter_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(),
        ),
    ]
