# Generated by Django 4.2.5 on 2023-10-11 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0025_alter_badge_code_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='/static/img/404.png', upload_to='Website/static/img/'),
        ),
        migrations.DeleteModel(
            name='Discount',
        ),
    ]
