# Generated by Django 4.2.4 on 2024-03-25 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0027_alter_product_image_discount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sandwich',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(default='/static/img/404.png', upload_to='static/img/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.category')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sandwich', to='App.badge')),
            ],
        ),
    ]
