# Generated by Django 4.2.4 on 2024-03-25 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0030_alter_sandwich_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge_Sandwich',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(default='<h5><span class="badge bg-primary ms-2">New</span></h5>', max_length=700)),
                ('code_price', models.CharField(default='<s>{{sandwich.price | safe}}</s><strong class="ms-2 text-danger">{{sandwich.get_price_with_discount | safe}}</strong>', max_length=700)),
            ],
        ),
    ]
