# Generated by Django 4.2.4 on 2024-03-25 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0032_alter_sandwich_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sandwich',
            name='image',
            field=models.ImageField(default='C:/Users/Sagnik Dey/Desktop/Website/Website/App/static/img', upload_to='C:/Users/Sagnik Dey/Desktop/Website/Website/App/static/img'),
        ),
    ]
